#!/usr/bin/python3

import sys
from src.computor import compute
from src.CmdParse import CmdParse


def usage():
    raise(ValueError(
        'computorV1: compute solution of equation up to degree 2 and basic calculator\
            \n\ttake only one argument that should be a string\
            \n\tex: ./computorV1  "5 * X^0 + 4 * X^1 - 9.3 * X^2 = 1 * X^0"'
    ))


def main(argv):
    number_of_args = len(argv)
    if number_of_args == 1:
        try:
            CmdParse().cmdloop()
        except KeyboardInterrupt:
            print()
            pass
    elif number_of_args > 2:
        raise SyntaxError('too many arguments')
    elif argv[1] == '-help' or argv[1] == '-h':
        usage()
    else:
        try:
            result = compute(argv[1])
            print(result)
        except ValueError:
            pass
        except SyntaxError as error:
            print(error)


try:
    main(sys.argv)
    sys.exit(False)
except (ValueError, SyntaxError) as error:
    print(error)
    sys.exit(True)
