#!/usr/bin/python3

from src.computor import Computor
import argparse
from src.CmdParse import CmdParse

if __name__ == "__main__":
    usage_message = 'compute solution of equation up to degree 2 and basic calculator.'
    parser = argparse.ArgumentParser(description=usage_message)
    parser.add_argument('-i', '--interactiv', action="store_true", help='interactive mode')
    parser.add_argument('equation', type=str, help='equation or calculus to solve. ex: ./computorV1  "5 * X^0 + 4 * X^1 - 9.3 * X^2 = 1 * X^0"')
    args = parser.parse_args()
    equation = args.equation

    if args.interactiv:
        try:
            CmdParse().cmdloop()
        except KeyboardInterrupt:
            print()
    else:
        Computor().main(equation)
